Repository Concordium/concordium.github.io, pull requests merged in 2021-12, with the labels that each got.

#263 Verification instructions
  requirements.txt
  source/mainnet/conf.py
  source/mainnet/net/index.rst
  source/mainnet/net/installation/cdw-verification-instructions/cdw-appimage.rst
  source/mainnet/net/installation/cdw-verification-instructions/cdw-deb.rst
  source/mainnet/net/installation/cdw-verification-instructions/cdw-rpm.rst
  source/mainnet/net/installation/client-verification-instructions/client-linux.rst
  source/mainnet/net/installation/downloads.rst
  source/mainnet/net/installation/verification-instructions.rst
  source/mainnet/variables.rst
  source/testnet/conf.py
Labels: [Prio] Medium

#335 grpc port edits
  source/mainnet/net/guides/run-node-ubuntu.rst
  source/shared/net/guides/run-node.rst
  source/testnet/net/guides/run-node-ubuntu.rst
Labels: documentation

#343 Desribes how to create an enterprise identity.
  source/mainnet/net/guides/enterprise-identities.rst
  source/mainnet/net/index.rst
Labels: documentation, [Prio] High

#342 Added concordium-client v3-0-4 to release notes - don't merge before enterprise identities release
  source/mainnet/net/resources/release-notes-mainnet.rst
Labels: [Status] On Hold
