Repository Concordium/concordium.github.io, pull requests merged in 2021-06, with the labels that each got.

#115 Run a node on Ubuntu and removal of troubleshooting
  source/testnet/guides/add-baker-desktop.rst
  source/testnet/guides/run-node-ubuntu.rst
  source/testnet/guides/run-node.rst
  source/testnet/index.rst
  source/testnet/installation/downloads.rst
  source/testnet/resources/troubleshooting.rst
Labels: [Prio] High, documentation

#119 Update run a node guide
  source/testnet/guides/run-node.rst
Labels: [Prio] High, documentation

#121 multi credentials on account
  source/testnet/desktop-wallet/install-ledger-app.rst
  source/testnet/guides/multi-credentials.rst
  source/testnet/index.rst
Labels: [Prio] High

#128 Multi-sig transfer and minor adjusments
  source/testnet/desktop-wallet/create-identity-desktop.rst
  source/testnet/desktop-wallet/get-started-desktop.rst
  source/testnet/guides/multisig-transfer.rst
  source/testnet/index.rst
  source/testnet/installation/get-the-app.rst
Labels: documentation

#132 export and import and various links and naming updates
  source/net/concepts/id-accounts.rst
  source/net/desktop-wallet/create-account-desktop.rst
  source/net/desktop-wallet/create-identity-desktop.rst
  source/net/desktop-wallet/export-import-desktop.rst
  source/net/desktop-wallet/get-started-desktop.rst
  source/net/desktop-wallet/install-ledger-app.rst
  source/net/guides/overview-baker-process.rst
  source/net/guides/run-node-ubuntu.rst
  source/net/index.rst
  source/net/installation/downloads.rst
  source/net/mobile-wallet/get-started.rst
  source/net/references/manage-accounts.rst
  source/net/references/transactions.rst
Labels: documentation

#166 New baker topics, updated index and change to make.bat
  make.bat
  source/mainnet/net/desktop-wallet/change-baker-stake.rst
  source/mainnet/net/desktop-wallet/change-restake-settings.rst
  source/mainnet/net/desktop-wallet/remove-baker.rst
  source/mainnet/net/desktop-wallet/update-baker-keys.rst
  source/mainnet/net/index.rst
  source/shared/net/concepts/concepts-baker.rst
  source/shared/net/desktop-wallet/change-baker-stake.rst
  source/shared/net/desktop-wallet/change-restake-settings.rst
  source/shared/net/desktop-wallet/remove-baker.rst
  source/shared/net/desktop-wallet/update-baker-keys.rst
  source/testnet/net/desktop-wallet/change-baker-stake.rst
  source/testnet/net/desktop-wallet/change-restake-settings.rst
  source/testnet/net/desktop-wallet/remove-baker.rst
  source/testnet/net/desktop-wallet/update-baker-keys.rst
  source/testnet/net/index.rst
Labels: documentation

#181 Desktop overviews
  source/mainnet/net/desktop-wallet/overview-addresses.rst
  source/mainnet/net/desktop-wallet/proposed-transactions.rst
  source/mainnet/net/desktop-wallet/settings-overview.rst
  source/mainnet/net/index.rst
  source/shared/net/desktop-wallet/get-started-desktop.rst
  source/shared/net/desktop-wallet/overview-addresses.rst
  source/shared/net/desktop-wallet/proposed-transactions.rst
  source/shared/net/desktop-wallet/settings-overview.rst
  source/testnet/net/desktop-wallet/overview-addresses.rst
  source/testnet/net/desktop-wallet/proposed-transactions.rst
  source/testnet/net/desktop-wallet/settings-overview.rst
  source/testnet/net/index.rst
Labels: documentation

#183 Ledger app installation edits
  source/shared/net/desktop-wallet/install-ledger-app.rst
Labels: documentation
