Repository Concordium/concordium.github.io, pull requests merged in 2023-10, with the labels that each got.

#875 Q3 2023 documentation refactoring
  public/extra/background-img.png
  public/extra/concordium-logo-dark.svg
  public/extra/testnet.html
  public/extra/testnet4.html
  source/_static/background-img.png
  source/_static/concordium-logo-dark.svg
  source/_static/concordium-logo-no-text.svg
  source/_static/concordium-logo.svg
  source/_static/css/style.css
  source/_static/css/tippy.css
  source/_static/discourse-brands.svg
  source/_static/fonts/Concordium Font - NB Akademie/NB Akademie Std-Bold.otf
  source/_static/fonts/Concordium Font - NB Akademie/NB Akademie Std-Light.otf
  source/_static/fonts/Concordium Font - NB Akademie/NB Akademie Std-Medium.otf
  source/_static/fonts/Concordium Font - NB Akademie/NB Akademie Std.otf
  source/_static/fonts/__MACOSX/._Concordium Font - NB Akademie
  source/_static/fonts/__MACOSX/Concordium Font - NB Akademie/._NB Akademie Std-Bold.otf
  source/_static/fonts/__MACOSX/Concordium Font - NB Akademie/._NB Akademie Std-Light.otf
  source/_static/fonts/__MACOSX/Concordium Font - NB Akademie/._NB Akademie Std-Medium.otf
  source/_static/fonts/__MACOSX/Concordium Font - NB Akademie/._NB Akademie Std.otf
  source/_static/style.css
  source/_templates/404.html
  source/_templates/analytics.html
  source/_templates/footer.html
  source/_templates/index.html
  source/_templates/layout.html
  source/_templates/navbar-logo.html
  source/_templates/navbar-menu.html
  source/_templates/theme-switcher.html
  source/mainnet/_templates/404.html
  source/mainnet/_templates/index.html
  source/mainnet/_templates/layout.html
  source/mainnet/conf.py
  source/mainnet/net/browser-wallet/setup-browser-wallet.rst
  source/mainnet/net/guides/become-baker.rst
  source/mainnet/net/guides/export-import.rst
  source/mainnet/net/guides/low-code-nft-marketplace/introduction.rst
  source/mainnet/net/guides/manage-wallets-lp.rst
  source/mainnet/net/guides/overview-desktop.rst
  source/mainnet/net/guides/setup-wallets-lp.rst
  source/mainnet/net/guides/wallet-faqs.rst
  source/mainnet/net/guides/wallets-lp.rst
  source/mainnet/net/index.rst
  source/mainnet/net/installation/downloads-testnet.rst
  source/mainnet/net/installation/downloads.rst
  source/mainnet/net/mobile-wallet/setup-mobile-wallet.rst
  source/mainnet/net/resources/legal.rst
  source/mainnet/smart-contracts/onboarding-guide-solana-developers/faq.rst
  source/mainnet/smart-contracts/onboarding-guide-solana-developers/index.rst
  source/mainnet/smart-contracts/onboarding-guide-solana-developers/overview.rst
Labels: preview

#869 Android 1.3.0 Release
  source/mainnet/net/guides/export-import.rst
  source/mainnet/net/release-notes/release-notes-lp.rst
Labels: documentation, UFT, preview

#863 iOS wallet CIS2 support
  source/mainnet/net/concepts/concepts-transactions.rst
  source/mainnet/net/guides/deciding-wallet.rst
  source/mainnet/net/guides/tokens.rst
  source/mainnet/net/release-notes/release-notes-lp.rst
Labels: documentation, UFT, preview

#895 Remove references to JSON-RPC in documentation
  source/mainnet/smart-contracts/tutorials/voting/voting-dapp.rst
  source/mainnet/smart-contracts/tutorials/wCCD/wCCD-front-end-set-up.rst
Labels: documentation

#877 Note for collector when using TLS
  source/mainnet/net/guides/run-node-macos.rst
  source/mainnet/net/guides/run-node-ubuntu.rst
  source/mainnet/net/guides/run-node-windows.rst
  source/mainnet/net/guides/run-node.rst
  source/mainnet/net/nodes/run-node-ubuntu.rst
Labels: documentation, Core Blockchain

#891 6.1.x Testnet node release
  source/mainnet/net/installation/downloads.rst
  source/mainnet/net/installation/previous-node-downloads.rst
  source/mainnet/net/release-notes/release-notes-lp.rst
  source/mainnet/variables.rst
Labels: documentation, Core Blockchain, preview

#844 SC testing library expansion: Explain setting up chain with builder and debug trace elements
  source/mainnet/smart-contracts/guides/integration-test-contract.rst
Labels: documentation, Core Blockchain

#900 Move downloads for mobile wallet
  source/mainnet/net/installation/downloads.rst
Labels: documentation, UFT, preview

#832 Add Finnish eID to identity topics
  source/mainnet/net/concepts/id-accounts.rst
  source/mainnet/net/guides/create-identity.rst
Labels: documentation, UFT

#909 Update cargo instructions for V0 SC
  source/mainnet/smart-contracts-v0/guides/setup-tools.rst
Labels: documentation

#914 Fix linux DW downloads
  source/mainnet/net/installation/downloads.rst
Labels: preview
