Repository Concordium/concordium.github.io, pull requests merged in 2024-04, with the labels that each got.

#1004 [AST-48] Added multi account voting explanation
  source/mainnet/net/images/voting/allow-list.png
  source/mainnet/net/images/voting/connected-account.png
  source/mainnet/net/voting/voting.rst
Labels: documentation, preview

#1007 Add CryptoX Android 1.0.0 release notes
  source/mainnet/net/release-notes/release-notes-lp.rst
Labels: preview

#763 Smart contract costs best practices
  Pipfile.lock
  source/mainnet/net/index.rst
  source/mainnet/smart-contracts/best-practices/costs.rst
  source/mainnet/smart-contracts/best-practices/index.rst
Labels: documentation, Core Blockchain, preview

#350 Added table of standard error codes to end of custom error codes topic.
  source/mainnet/smart-contracts-v0/guides/custom-errors.rst
  source/mainnet/smart-contracts/guides/custom-errors.rst
Labels: documentation, Core Blockchain, preview

#1012 Explain migration flow from mw-gen1 to cryptox in voting doc
  source/mainnet/net/voting/voting.rst
Labels: preview
